[project]
name = "chatapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.23.0",
    "groq>=0.29.0",
    "openai>=1.84.0",
    "streamlit>=1.45.1",
]
