services:
  expenses-app:
    build: .
    ports:
      - "8504:8504"
    env_file:
      - .env
    volumes:
      - ./data/:/data/
      - ./app/:/app/
    working_dir: /app
    restart: unless-stopped