services:
  chat-bot:
    container_name: chat-bot
    build: ./ChatAPI
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8501"
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data/:/data/
      - ./ChatAPI/:/app/
    working_dir: /app
    restart: unless-stopped

  expenses-app:
    container_name: expenses-app
    build: ./Household_Expenses
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8502"
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - ./data/:/data/
      - ./Household_Expenses/:/app/
    working_dir: /app
    restart: unless-stopped

  bus-app:
    container_name: bus-app
    build: ./BusApp
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8503"
    ports:
      - "8503:8503"
    env_file:
      - .env
    volumes:
      - ./BusApp/:/app/
    working_dir: /app
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chat-bot
      - expenses-app
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot