services:
  chat-bot:
    container_name: chat-bot
    build: ./ChatAPI
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8501"
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data/:/data/
      - ./ChatAPI/:/app/
    working_dir: /app
    restart: unless-stopped

  expenses-app:
    container_name: expenses-app
    build: ./Household_Expenses
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8502"
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - ./data/:/data/
      - ./Household_Expenses/:/app/
    working_dir: /app
    restart: unless-stopped

  bus-app:
    container_name: bus-app
    build: ./BusApp
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "8503"
    ports:
      - "8503:8503"
    env_file:
      - .env
    volumes:
      - ./BusApp/:/app/
    working_dir: /app
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chat-bot
      - expenses-app
      - bus-app
      - oauth2-proxy
    restart: unless-stopped

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "4180:4180"
    env_file:
      - ./nginx/oauth2_proxy.env
    volumes:
      - ./nginx/allowed_emails.txt:/etc/oauth2_proxy/allowed_emails.txt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot